// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dto

import (
	"time"
)

type ReservasFactura struct {
	Idfactura  int32  `json:"idfactura"`
	Fechafact  string `json:"fechafact"`
	Metodopago string `json:"metodopago"`
	Iva        string `json:"iva"`
	Descuento  string `json:"descuento"`
	Subtotal   string `json:"subtotal"`
	Total      string `json:"total"`
	Reserva    int32  `json:"reserva"`
}

type ReservasPersona struct {
	Idpersona int32     `json:"idpersona"`
	Nombre    string    `json:"nombre"`
	Apellido1 string    `json:"apellido_1"`
	Apellido2 string    `json:"apellido_2"`
	Fechanac  time.Time `json:"fechanac"`
	Telefono  string    `json:"telefono"`
	Correo    string    `json:"correo"`
}

type ReservasReserva struct {
	Numreserva       int32  `json:"numreserva"`
	Fechareserva     string `json:"fechareserva"`
	Horareserva      string `json:"horareserva"`
	Cantidadpersonas int32  `json:"cantidadpersonas"`
	Tour             int32  `json:"tour"`
	Usuario          string `json:"usuario"`
	Persona          int32  `json:"persona"`
	Transfer         int32  `json:"transfer"`
}

type ReservasTour struct {
	Idtour         int32  `json:"idtour"`
	Nombre         string `json:"nombre"`
	Descripcion    string `json:"descripcion"`
	Tipo           string `json:"tipo"`
	Disponibilidad int8   `json:"disponibilidad"`
	Preciobase     string `json:"preciobase"`
	Ubicacion      string `json:"ubicacion"`
}

type ReservasTransfer struct {
	Idtransfer int32  `json:"idtransfer"`
	Tipo       string `json:"tipo"`
	Capacidad  int32  `json:"capacidad"`
}

type ReservasUsuario struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	Rol       string `json:"rol"`
	Idpersona int32  `json:"idpersona"`
}
